# Generated by Django 5.2.8 on 2025-11-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('RDB', 'Road Banner'), ('FBG', 'Facebook Group'), ('JSD', 'Justdial'), ('WAP', 'Whatsapp'), ('OTH', 'Other')], default='OTH', max_length=3)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CON', 'Contacted'), ('INT', 'Interested'), ('NOT', 'Not Interested'), ('CAN', 'Cancelled'), ('JND', 'Joined'), ('OTH', 'Other')], default='NEW', max_length=3)),
                ('is_added', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
