# Generated by Django 5.2.8 on 2025-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0003_alter_category_parent_business'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Businesses'},
        ),
        migrations.AlterField(
            model_name='business',
            name='biz_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
