# Generated by Django 5.2.8 on 2025-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_business_address_business_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='year_of_est',
            field=models.IntegerField(blank=True, max_length=4, null=True),
        ),
    ]
