# Generated by Django 5.2.8 on 2025-11-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_business_year_of_est'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='attributes',
            field=models.ManyToManyField(blank=True, null=True, related_name='businesses', to='business.attribute'),
        ),
        migrations.AlterField(
            model_name='business',
            name='year_of_est',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
