# Generated by Django 5.2.8 on 2025-11-29 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0012_business_attributes_alter_business_year_of_est'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='image_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='business.attribute'),
        ),
    ]
