# Generated by Django 5.2.8 on 2025-11-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_business_image_id_alter_business_attributes'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_keywords',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
