# Generated by Django 5.2.8 on 2025-11-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_category_meta_description_category_meta_keywords_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='location',
        ),
        migrations.AddField(
            model_name='business',
            name='locations',
            field=models.ManyToManyField(blank=True, to='business.location'),
        ),
    ]
