# Generated by Django 5.2.8 on 2025-11-30 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0015_remove_business_location_business_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='business.business')),
            ],
        ),
    ]
